### ISSUE TITLE
tar: File removed before we read it

### ISSUE THREAD

**Issue by dbajuliano** [dbajuliano/postgres-dba-scripts#1]
https://github.com/julianodba/postgres-dba-scripts/blob/b8bee5840fa9a94ff8bf5d3c8401380703a56665/pg_backup.sh#L32

Not sure if it is a bug or just warnings but I am concerned and looking to find a way to fix it or a smart way to do this parallel compression.

Getting these on randomly days so far:
tar: pg/backup_label.old: File removed before we read it
tar: pg/current_logfiles: File removed before we read it
tar: pg/recovery.done: File removed before we read it
tar: pg/recovery.conf: File removed before we read it
tar: pg/pg_hba.conf: File removed before we read it

**Comment by julianodba** [comment]
Removed "pg" argument from "--remove-files" as explained by RhodiumToad from #postgresql IRC channel.

"--remove-files doesn't take any argument
it just removes files added to the archive"

keeping test for a couple of days
